# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af7d808bd1fb2345e917ec96e9c3b9a376e4f009fc7279ea208eebcc179f1b6867b222901bf5c1644e0c73fac2d8f64d140407e89315dca5e6827456a973eaf

test:
  secret_key_base: 621ae93ab71a5496036b2313d84067745f9e52afdecbaa36fc506a45cfb04e29d7af2c7d237a947b570aad03772ea59a5de83d1c27bee05d8cb2614dee04ef20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
